### ISSUE TITLE
Trying to wire up motor encoder with dc motor

### ISSUE THREAD

**Issue by tmand54** [sinricpro/esp8266-esp32-sdk#323]

**Comment by sivar2311** [comment]
Hi @tmand54 !
I don't understand the question about the encoder in relation to SinricPro. 
What do you want SinricPro to do with your encoder? 
Can you describe your project in more detail?

**Comment by tmand54** [comment]
Hello @sivar2311 ,

The project is to control blinds to open and close.

So the encoder reads the rotation of the motor essentially the steps of the motor.

The output would be controlling the motor by sending a HIGH or LOW signal to the motor driver to have it rotate CW or CCW.

I need to put a limit based on the number of steps from 0 to X, X being the max height of the blinds.

**Comment by sivar2311** [comment]
You are using stepper motors in your project. Therefore, the number of steps taken is known to you exactly and does not have to be reported back by an additional (rotary?)encoder. The number of steps made can be determined by simply counting the HIGH / LOW outputs.

It would be better to use a mechanical or optical limit switch that tells you exactly when the limit is reached and the blind is in a defined start or end position. 

If you know the number of steps for the required distance, you could also use a custom device in SinricPro that uses a RangeController. There you can specify the number of maximum steps or a length. If you use a length specification, your Sketch would only have to convert this into motor steps.

**Comment by tmand54** [comment]
Its a DC motor with a rotary encol298der driven by a L298N motor driver, the program sends a high/low output, and the return signal which reads the steps dictacted by the rotary encoder of the DC motor. When 1000 steps (per se) are reached it is in the closed position. 0 steps would be the full open position.

**Comment by sivar2311** [comment]
Now I understand. 
So you are not using stepper motors.

But if I read your original code correctly, it does not implement the behaviour you want (1000 steps per direction).
Do you already have a (non SinricPro) sketch that implements your desired behaviour?

**Comment by tmand54** [comment]
At the moment, I have the motor turning on. Still new at this. I'm still trying to have the encoder working so it can give me a steps count. Once I have the steps count I can tell Sinric to CLOSE and it will go from 0-> 1000 steps and when I tell Sinric to open it will go from 1000 steps to 0 steps.

I had some YAML code , see below.

```

globals:
   - id: blind_max
     type: int
     restore_value: yes
     initial_value: '93300' #change value, 0 at top, max on bottom. Change for height for cat.
    
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: D1 #gpio5
    pin_b: D2 #gpio4
    id: blind_steps

switch:
  - platform: gpio
    pin: D6 #gray,gpio12
    name: "Blind S2"
    id: "blind_s2"
    interlock: [blind_s1]

  - platform: gpio
    pin: D5 #white,gpio14
    name: "Blind S1"
    id: "blind_s1"
    interlock: [blind_s2]

cover:
  - platform: template
    name: "Back Blinds"
    id: blind_cover
    device_class: shade
    has_position: true

    close_action:
      - switch.turn_off: blind_s1
      - switch.turn_on: blind_s2
      - cover.template.publish:
          id: blind_cover
          current_operation: CLOSING
          position: !lambda |-
            float pos = id(blind_steps).state / id(blind_max);
            return pos < 0 ? 0 : pos;
      - wait_until: 
          lambda: 'return id(blind_steps).state >= id(blind_max);'
      - switch.turn_off: blind_s2
      - cover.template.publish:
          id: blind_cover
          state: CLOSED
          current_operation: IDLE

    open_action:
      - switch.turn_on: blind_s1
      - switch.turn_off: blind_s2
      - cover.template.publish:
          id: blind_cover
          current_operation: OPENING
          position: !lambda |-
            float pos = id(blind_steps).state / id(blind_max);
            return pos > 1 ? 1 : pos;
              
      - wait_until:
          lambda: 'return id(blind_steps).state <= 0;'
      - switch.turn_off: blind_s1
      - cover.template.publish:
          id: blind_cover
          state: OPEN
          current_operation: IDLE
          
    stop_action:
      then:
        - switch.turn_off: blind_s1
        - switch.turn_off: blind_s2
        - cover.template.publish:
            id: blind_cover
            position: !lambda 'return id(blind_steps).state / id(blind_max);' 
            current_operation: IDLE

    position_action:
          - if:
              condition:
                lambda: 'return id(blind_steps).state / id(blind_max) < pos;'
              then:
                - switch.turn_on: blind_s1
                - switch.turn_off: blind_s2
                - cover.template.publish:
                    id: blind_cover
                    current_operation: OPENING
                - wait_until:
                    lambda: 'return id(blind_steps).state >= pos * id(blind_max);'
                - switch.turn_off: blind_s1
                - cover.template.publish:
                    id: blind_cover
                    current_operation: IDLE
                    position: !lambda 'return id(blind_steps).state / id(blind_max);'
              else:
                - switch.turn_off: blind_s1
                - switch.turn_on: blind_s2
                - cover.template.publish:
                    id: blind_cover
                    current_operation: CLOSING
                - wait_until:
                    lambda: 'return id(blind_steps).state <= pos * id(blind_max);'
                - switch.turn_off: blind_s2
                - cover.template.publish:
                    id: blind_cover
                    current_operation: IDLE
                    position: !lambda 'return id(blind_steps).state / id(blind_max);'
    
```
